AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nova-note-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  CorsAllowOrigin:
    Type: String
    Default: "'*'"
    Description: 'CORS Allow Origin header value'

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: nova-note-api
      StageName: Prod
      Cors:
        AllowOrigin: !Ref CorsAllowOrigin
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/hello-world.helloWorldHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          CLIENT_ORIGIN: !Ref CorsAllowOrigin
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello
            Method: get

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
